insert into medicos (nombre, especialidad, matricula) values ('Doralia', 'Product Management', 504344);
insert into medicos (nombre, especialidad, matricula) values ('Daisie', 'Business Development', 526568);
insert into medicos (nombre, especialidad, matricula) values ('Naomi', 'Human Resources', 345149);
insert into medicos (nombre, especialidad, matricula) values ('Minnnie', 'Sales', 212545);
insert into medicos (nombre, especialidad, matricula) values ('Rockey', 'Legal', 321480);
insert into medicos (nombre, especialidad, matricula) values ('Kermie', 'Research and Development', 443616);
insert into medicos (nombre, especialidad, matricula) values ('Igor', 'Business Development', 605518);
insert into medicos (nombre, especialidad, matricula) values ('Anna-diane', 'Sales', 437594);
insert into medicos (nombre, especialidad, matricula) values ('Reinhold', 'Services', 148151);
insert into medicos (nombre, especialidad, matricula) values ('Coralie', 'Research and Development', 653526);
insert into medicos (nombre, especialidad, matricula) values ('See', 'Accounting', 352153);
insert into medicos (nombre, especialidad, matricula) values ('Skippie', 'Legal', 591196);
insert into medicos (nombre, especialidad, matricula) values ('Zilvia', 'Product Management', 188965);
insert into medicos (nombre, especialidad, matricula) values ('Elroy', 'Training', 478076);
insert into medicos (nombre, especialidad, matricula) values ('Bar', 'Training', 145073);
insert into medicos (nombre, especialidad, matricula) values ('Gasparo', 'Training', 379287);
insert into medicos (nombre, especialidad, matricula) values ('Abbe', 'Accounting', 147991);
insert into medicos (nombre, especialidad, matricula) values ('Idell', 'Marketing', 299469);
insert into medicos (nombre, especialidad, matricula) values ('Lilli', 'Business Development', 639785);
insert into medicos (nombre, especialidad, matricula) values ('Sigismond', 'Legal', 388679);
insert into medicos (nombre, especialidad, matricula) values ('Marietta', 'Legal', 614171);
insert into medicos (nombre, especialidad, matricula) values ('Bertie', 'Training', 292762);
insert into medicos (nombre, especialidad, matricula) values ('Seka', 'Accounting', 598266);
insert into medicos (nombre, especialidad, matricula) values ('Jarrod', 'Marketing', 157830);
insert into medicos (nombre, especialidad, matricula) values ('Darby', 'Support', 312864);
insert into medicos (nombre, especialidad, matricula) values ('Ad', 'Sales', 171477);
insert into medicos (nombre, especialidad, matricula) values ('Franny', 'Product Management', 132807);
insert into medicos (nombre, especialidad, matricula) values ('Noll', 'Legal', 432435);
insert into medicos (nombre, especialidad, matricula) values ('Dalston', 'Sales', 307422);
insert into medicos (nombre, especialidad, matricula) values ('Rica', 'Training', 136607);
insert into medicos (nombre, especialidad, matricula) values ('Cherianne', 'Support', 171070);
insert into medicos (nombre, especialidad, matricula) values ('Murielle', 'Engineering', 318155);
insert into medicos (nombre, especialidad, matricula) values ('Hettie', 'Engineering', 211073);
insert into medicos (nombre, especialidad, matricula) values ('Anselma', 'Accounting', 132610);
insert into medicos (nombre, especialidad, matricula) values ('Clem', 'Product Management', 202816);
insert into medicos (nombre, especialidad, matricula) values ('Bliss', 'Services', 309610);
insert into medicos (nombre, especialidad, matricula) values ('Brig', 'Services', 441173);
insert into medicos (nombre, especialidad, matricula) values ('Ilysa', 'Training', 566954);
insert into medicos (nombre, especialidad, matricula) values ('Tresa', 'Sales', 407217);
insert into medicos (nombre, especialidad, matricula) values ('Aidan', 'Product Management', 461290);
insert into medicos (nombre, especialidad, matricula) values ('Shelby', 'Training', 303044);
insert into medicos (nombre, especialidad, matricula) values ('Alexis', 'Support', 325279);
insert into medicos (nombre, especialidad, matricula) values ('Leda', 'Support', 194151);
insert into medicos (nombre, especialidad, matricula) values ('Denyse', 'Services', 311640);
insert into medicos (nombre, especialidad, matricula) values ('Hilda', 'Training', 569175);
insert into medicos (nombre, especialidad, matricula) values ('Nichole', 'Sales', 126690);
insert into medicos (nombre, especialidad, matricula) values ('Babs', 'Sales', 598419);
insert into medicos (nombre, especialidad, matricula) values ('Myer', 'Legal', 203938);
insert into medicos (nombre, especialidad, matricula) values ('Ivory', 'Human Resources', 318378);
insert into medicos (nombre, especialidad, matricula) values ('Adair', 'Support', 508001);
